classification_type: input_block
dataset:
  name: message_repetition
  hf_dataset: arnonmz/BARRED
  cluster: A user repeats or rephrases the same message 3 times
  labels: ['True', 'False']
  evaluator:
    llm_config:
      type: azure
      name: gpt-4-1-nano-2025-04-14-ft-7a05fea651cb4b55b4eee936cfd2b552
      temperature: 0
    #llm_config:
      #type: azure
      #name: gpt-4.1-mini
      #temperature: 0
    #llm_config:
      #type: azure
      #name: gpt-5-mini
      #temperature: 1
      #model_kwargs:
        #reasoning_effort: "medium"
    #slm_model: unsloth/Qwen2.5-7B
out_dir: ../output/results
